### ISSUE TITLE
测试到达120万条时，出现无法开始

### ISSUE THREAD

**Issue by wjqsyrs** [zgcwkjOpenProject/TestBaiduPassword#3]

**Comment by zgcwkj** [comment]
额，线程的数量是很大吗？大于200以上？

**Comment by zgcwkj** [comment]
兄弟，你人呢？

**Comment by lanyou2017** [comment]
100啊，跑出来的log.ini很大，我怀疑是这个问题

**Comment by lanyou2017** [comment]
我在同等网络的情况下重新创建了一个项目，结果是可以跑的，不过之前的log.ini，我看了有很多网络未连接，因为是笔记本用手机wifi。

**Comment by zgcwkj** [comment]
log.ini是追加的，无论大小，都没问题的，
如果可以把上次整个项目的文件压缩发我一份，试试

**Comment by lanyou2017** [comment]
我给删了。。。。我争取继续跑程序，能不能重现吧。话说这么密码是全覆盖的吗？0000-zzzz
虽然后端我看了那个hash的密码生成，像是全覆盖的，但是我是java的，c#有些看不懂。

**Comment by zgcwkj** [comment]
密码全部跑的，如果因为网络等因素，密码不会跳过的，只会不断的参数那个密码
